# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyAmerica' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyAmerica
  pod ‘Flurry-iOS-SDK/FlurrySDK’

  target 'MyAmericaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
